### PR TITLE
Corrected course code in readme

### PR DESCRIPTION
**Pull request by 414owen**
I feel this is an important step in the right direction.
Good luck with the rest of your module.

### CODE REVIEW

**Comment by roryflynn** [comment]
@414owen could you write some unit tests for your PR please

**Comment by 414owen** [comment]
@roryflynn I appreciate your concern over the validity of my markdown. Please let me know whether the attached screenshot satisfies your hunger for proof-of-correctness. If it doesn't please suggest a further course of action.

2017-10-17-154344_1920x1080_scrot

**Comment by roryflynn** [comment]
@414owen great, could you make your test run in headless Chrome? Our build system doesn't have support for human agents yet.

**Comment by eddiebergman** [comment]
@414owen I tried running this screenshot as a test but I can not read. Could you please include a more friendly "text-to-speech" version of your change

**Pull request merged**
